services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    networks:
      - app-network

  frontend:
    build: ./frontend
    ports:
      - "8080:8000"
    networks:
      - app-network

networks:
  app-network:
